version: "3"

volumes:
  site-mysql:

services:
  nginx:
    build: ./nginx
    links:
      - php-fpm:php
    networks:
      - site
    volumes:
      - ./data/logs/nginx:/var/log/nginx
      - ./data/site:/var/www/site
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  php-fpm:
    build: ./php74-fpm
    links:
      - mysql
    networks:
      - site
    volumes:
      - ./data/site:/var/www/site
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  php-cli:
    build: ./php74-cli
    links:
      - mysql
    networks:
      - site
    volumes:
      - ./data/site:/var/www/site
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  mysql:
    build: ./mysql
    environment:
      MYSQL_DATABASE: bitrixdb
      MYSQL_USER: bitrixdb
      MYSQL_PASSWORD: yjl3pPmdeM
      MYSQL_ROOT_PASSWORD: yjl3pPmdeM
    networks:
      - site
    volumes:
      - site-mysql:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  sphinx:
    build: ./sphinx
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
        - /etc/localtime:/etc/localtime:ro
    networks:
        - site
    restart: unless-stopped

  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - site
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt

networks:
  site:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8