services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./logs/nginx/:/var/log/nginx/
      - ./www/:/var/www/public
    networks:
      - site
      - proxynet
    environment:
      TZ: Asia/Yekaterinburg
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site.tls.certresolver=le"
      - "traefik.http.routers.site.rule=Host(`${SITE_DOMAIN}`) || Host(`www.${SITE_DOMAIN}`)"
      - "traefik.http.routers.site.tls.domains[0].main=${SITE_DOMAIN}"
      - "traefik.http.routers.site.tls.domains[0].sans=www.${SITE_DOMAIN}"
      
  php: 
    build: ./${PHP_VERSION}
    restart: always
    networks:
      - site
    volumes:
      - ./logs/php/:/var/log/php/
      - ./www/:/var/www/public

  cron: 
    build: ./${PHP_VERSION}
    restart: always
    command: cron -f && tail -f /var/log/cron.log
    networks:
      - site
    volumes:
      - ./logs/cron:/var/log
      - ./www/:/var/www/public

  mysql:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    networks:
      - site
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  site:
  proxynet:
    external: true
